version: '2'
services:
  db:
    image: postgres:9.5.3
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: bdss
      POSTGRES_USER: bdss
      POSTGRES_PASSWORD: topsecret
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://bdss:topsecret@db/bdss
      SESSION_KEY:
    links:
      - db
  web:
    image: nginx:1.10
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    links:
      - app
